/**
 * @file autosar_types.hpp
 * @brief Basic AUTOSAR type definitions and constants for learning
 * 
 * This file provides simplified AUTOSAR-style type definitions that would
 * typically be generated by AUTOSAR tooling in a production environment.
 */

#ifndef AUTOSAR_TYPES_HPP
#define AUTOSAR_TYPES_HPP

#include <cstdint>
#include <string>
#include <memory>
#include <functional>

namespace autosar {

// AUTOSAR platform types (typically defined by AUTOSAR Platform)
using boolean = bool;
using uint8 = std::uint8_t;
using uint16 = std::uint16_t;
using uint32 = std::uint32_t;
using sint8 = std::int8_t;
using sint16 = std::int16_t;
using sint32 = std::int32_t;
using float32 = float;
using float64 = double;
using uint64 = std::uint64_t;

// Return codes used throughout AUTOSAR
enum class Std_ReturnType : uint8 {
    E_OK = 0x00,        // Success
    E_NOT_OK = 0x01     // General error
};

// Port directions
enum class PortDirection {
    SENDER,
    RECEIVER
};

// Interface types
enum class InterfaceType {
    SENDER_RECEIVER,
    CLIENT_SERVER
};

// SWC execution states
enum class SWCState {
    STOPPED,
    RUNNING,
    ERROR
};

// Timing constants (in milliseconds)
constexpr uint32 ENGINE_CYCLE_TIME_MS = 100;  // 10Hz
constexpr uint32 BODY_CYCLE_TIME_MS = 500;    // 2Hz
constexpr uint32 RTE_CYCLE_TIME_MS = 10;      // 100Hz

// CAN message IDs (automotive standard ranges)
namespace can_ids {
    constexpr uint32 ENGINE_RPM = 0x110;
    constexpr uint32 ENGINE_TEMP = 0x111;
    constexpr uint32 DOOR_STATUS = 0x220;
    constexpr uint32 LIGHT_STATUS = 0x230;
}

// Data element definitions for interfaces
struct EngineData {
    uint16 rpm;
    uint8 temperature;
    uint8 throttle_position;
    
    EngineData() : rpm(800), temperature(90), throttle_position(0) {}
};

struct DoorStatus {
    boolean front_left_open;
    boolean front_right_open;
    boolean rear_left_open;
    boolean rear_right_open;
    
    DoorStatus() : front_left_open(false), front_right_open(false),
                   rear_left_open(false), rear_right_open(false) {}
};

struct LightControl {
    boolean headlights_on;
    boolean turn_signal_left;
    boolean turn_signal_right;
    
    LightControl() : headlights_on(false), turn_signal_left(false),
                     turn_signal_right(false) {}
};

} // namespace autosar

#endif // AUTOSAR_TYPES_HPP