/**
 * @file autosar_types.hpp
 * @brief Basic AUTOSAR type definitions and constants for learning
 * 
 * This file provides simplified AUTOSAR-style type definitions that would
 * typically be generated by AUTOSAR tooling in a production environment.
 * 
 * C++20 Features Used:
 * - Concepts for type safety
 * - Designated initializers
 * - consteval for compile-time constants
 */

#ifndef AUTOSAR_TYPES_HPP
#define AUTOSAR_TYPES_HPP

#include <cstdint>
#include <string>
#include <memory>
#include <functional>
#include <concepts>
#include <type_traits>

namespace autosar {

// AUTOSAR platform types (typically defined by AUTOSAR Platform)
using boolean = bool;
using uint8 = std::uint8_t;
using uint16 = std::uint16_t;
using uint32 = std::uint32_t;
using sint8 = std::int8_t;
using sint16 = std::int16_t;
using sint32 = std::int32_t;
using float32 = float;
using float64 = double;
using uint64 = std::uint64_t;

// Return codes used throughout AUTOSAR
enum class Std_ReturnType : uint8 {
    E_OK = 0x00,        // Success
    E_NOT_OK = 0x01     // General error
};

// Port directions
enum class PortDirection {
    SENDER,
    RECEIVER
};

// Interface types
enum class InterfaceType {
    SENDER_RECEIVER,
    CLIENT_SERVER
};

// SWC execution states
enum class SWCState {
    STOPPED,
    RUNNING,
    ERROR
};

// C++20 Concepts for AUTOSAR type safety
template<typename T>
concept AutosarDataType = requires {
    sizeof(T) <= 8;  // CAN message size constraint
    std::is_trivially_copyable_v<T>;
    std::is_standard_layout_v<T>;
};

template<typename T>
concept AutosarNumericType = AutosarDataType<T> && std::is_arithmetic_v<T>;

template<typename T>
concept AutosarStructType = AutosarDataType<T> && std::is_class_v<T>;

// Timing constants (in milliseconds) - compile-time evaluation
consteval uint32 get_engine_cycle_time() { return 100; }  // 10Hz
consteval uint32 get_body_cycle_time() { return 500; }    // 2Hz
consteval uint32 get_rte_cycle_time() { return 10; }      // 100Hz

constexpr uint32 ENGINE_CYCLE_TIME_MS = get_engine_cycle_time();
constexpr uint32 BODY_CYCLE_TIME_MS = get_body_cycle_time();
constexpr uint32 RTE_CYCLE_TIME_MS = get_rte_cycle_time();

// CAN message IDs (automotive standard ranges)
namespace can_ids {
    constexpr uint32 ENGINE_RPM = 0x110;
    constexpr uint32 ENGINE_TEMP = 0x111;
    constexpr uint32 DOOR_STATUS = 0x220;
    constexpr uint32 LIGHT_STATUS = 0x230;
}

// Data element definitions for interfaces with C++20 designated initializers
struct EngineData {
    uint16 rpm = 800;              // Idle RPM default
    uint8 temperature = 90;        // Normal operating temperature
    uint8 throttle_position = 0;   // Closed throttle default
    
    // C++20 designated initializer support
    static constexpr EngineData idle() {
        return EngineData{
            .rpm = 800,
            .temperature = 90,
            .throttle_position = 0
        };
    }
    
    static constexpr EngineData running(uint16 engine_rpm) {
        return EngineData{
            .rpm = engine_rpm,
            .temperature = 95,
            .throttle_position = 25
        };
    }
};

struct DoorStatus {
    boolean front_left_open = false;
    boolean front_right_open = false;
    boolean rear_left_open = false;
    boolean rear_right_open = false;
    
    // C++20 designated initializer support
    static constexpr DoorStatus all_closed() {
        return DoorStatus{
            .front_left_open = false,
            .front_right_open = false,
            .rear_left_open = false,
            .rear_right_open = false
        };
    }
    
    static constexpr DoorStatus driver_open() {
        return DoorStatus{
            .front_left_open = true,
            .front_right_open = false,
            .rear_left_open = false,
            .rear_right_open = false
        };
    }
};

struct LightControl {
    boolean headlights_on = false;
    boolean turn_signal_left = false;
    boolean turn_signal_right = false;
    
    // C++20 designated initializer support
    static constexpr LightControl all_off() {
        return LightControl{
            .headlights_on = false,
            .turn_signal_left = false,
            .turn_signal_right = false
        };
    }
    
    static constexpr LightControl headlights_only() {
        return LightControl{
            .headlights_on = true,
            .turn_signal_left = false,
            .turn_signal_right = false
        };
    }
};

} // namespace autosar

#endif // AUTOSAR_TYPES_HPP