/**
 * @file body_swc.hpp
 * @brief Body Control Software Component - AUTOSAR C++ Implementation
 * 
 * Demonstrates a Body Control Module SWC with:
 * - Door status monitoring and control
 * - Light control (headlights, turn signals)
 * - Window position management
 * - Inter-SWC communication via ports
 * - Realistic automotive behavior simulation
 */

#ifndef BODY_SWC_HPP
#define BODY_SWC_HPP

#include "swc_base.hpp"
#include "can_interface.hpp"
#include "autosar_types.hpp"
#include <random>
#include <chrono>
#include <memory>
#include <array>

namespace autosar {

/**
 * @brief Door Status Interface - defines contract for door communication
 */
class DoorStatusInterface : public Interface {
public:
    DoorStatusInterface() : Interface("DoorStatusInterface", InterfaceType::SENDER_RECEIVER) {}
    ~DoorStatusInterface() override = default;
};

/**
 * @brief Light Control Interface - defines contract for lighting system
 */
class LightControlInterface : public Interface {
public:
    LightControlInterface() : Interface("LightControlInterface", InterfaceType::SENDER_RECEIVER) {}
    ~LightControlInterface() override = default;
};

/**
 * @brief Window position data structure
 */
struct WindowPosition {
    uint8 front_left;     // 0-100% open
    uint8 front_right;
    uint8 rear_left;
    uint8 rear_right;
    
    WindowPosition() : front_left(0), front_right(0), rear_left(0), rear_right(0) {}
};

/**
 * @brief Body Control Software Component
 * 
 * This SWC represents the application layer of a Body Control Module (BCM).
 * In a real vehicle, this would manage comfort and convenience features.
 * 
 * Responsibilities:
 * - Monitor door status (open/closed)
 * - Control lighting systems (headlights, turn signals)
 * - Manage window positions
 * - Receive engine data for auto features
 * - Send status updates to other ECUs via CAN
 * 
 * AUTOSAR Ports:
 * - DoorStatusPort (Sender): Sends door status to other SWCs
 * - LightControlPort (Receiver): Receives light commands from HMI
 * - EngineDataPort (Receiver): Receives engine data for auto features
 */
class BodyControlSWC : public SoftwareComponent {
public:
    /**
     * @brief Constructor
     * @param can_interface CAN communication interface
     */
    explicit BodyControlSWC(std::shared_ptr<CANInterface> can_interface);
    
    /**
     * @brief Destructor
     */
    ~BodyControlSWC() override = default;
    
    // AUTOSAR SWC lifecycle
    Std_ReturnType initialize() override;
    
    // Main runnable entity - called periodically by RTE/OS
    void runnable() override;
    
    // Port access functions (would typically be generated by AUTOSAR tools)
    Std_ReturnType writeDoorStatus(const DoorStatus& status);
    Std_ReturnType readDoorStatus(DoorStatus& status) const;
    Std_ReturnType readLightControl(LightControl& control) const;
    Std_ReturnType readEngineData(EngineData& data) const;
    
    // Manual control functions (for HMI simulation)
    void setLightControl(const LightControl& control);
    void setDoorOpen(uint8 door_index, boolean is_open);
    void setWindowPosition(uint8 window_index, uint8 position);
    
    // Getters for current state (for debugging/monitoring)
    const DoorStatus& getCurrentDoorStatus() const { return current_door_status_; }
    const LightControl& getCurrentLightControl() const { return current_light_control_; }
    const WindowPosition& getCurrentWindowPosition() const { return current_window_position_; }
    uint32 getCycleCount() const { return cycle_count_; }
    
private:
    // CAN communication
    std::shared_ptr<CANInterface> can_interface_;
    
    // Body control state
    DoorStatus current_door_status_;
    LightControl current_light_control_;
    WindowPosition current_window_position_;
    EngineData received_engine_data_;
    boolean engine_data_valid_;
    
    // Auto features configuration
    boolean auto_lights_enabled_;
    boolean received_new_engine_data_;
    
    // Simulation state
    std::mt19937 random_generator_;
    std::uniform_real_distribution<float> activity_probability_;
    std::uniform_int_distribution<int> door_selection_;
    std::uniform_int_distribution<int> window_position_;
    
    // Timing and scheduling
    std::chrono::steady_clock::time_point last_execution_;
    uint32 cycle_count_;
    
    // Configuration constants
    static constexpr uint8 NUM_DOORS = 4;
    static constexpr uint8 NUM_WINDOWS = 4;
    static constexpr float DOOR_ACTIVITY_CHANCE = 0.02f;    // 2% chance per cycle
    static constexpr float WINDOW_ACTIVITY_CHANCE = 0.01f;  // 1% chance per cycle
    static constexpr uint16 AUTO_LIGHT_RPM_THRESHOLD = 1000; // RPM for auto headlights
    
    // Private methods
    void simulateBodyActivity();
    void processAutoFeatures();
    void sendBodyDataViaCAN();
    void updatePortData();
    void receiveEngineDataFromPort();
    
    // Simulation helpers
    void simulateDoorActivity();
    void simulateWindowActivity();
    void processAutoLights();
    
    // Utility functions
    boolean* getDoorStatusPointer(uint8 door_index);
    uint8* getWindowPositionPointer(uint8 window_index);
    const char* getDoorName(uint8 door_index) const;
    const char* getWindowName(uint8 window_index) const;
};

} // namespace autosar

#endif // BODY_SWC_HPP