/**
 * @file engine_swc.hpp
 * @brief Engine Software Component - AUTOSAR C++ Implementation
 * 
 * Demonstrates a production-style Engine Control SWC with:
 * - Proper AUTOSAR ports and interfaces
 * - CAN communication through BSW layer
 * - Real-time behavior simulation
 * - Modern C++ automotive practices
 */

#ifndef ENGINE_SWC_HPP
#define ENGINE_SWC_HPP

#include "swc_base.hpp"
#include "can_interface.hpp"
#include <random>
#include <chrono>
#include <memory>

namespace autosar {

/**
 * @brief Engine Data Interface - defines contract for engine communication
 */
class EngineDataInterface : public Interface {
public:
    EngineDataInterface() : Interface("EngineDataInterface", InterfaceType::SENDER_RECEIVER) {}
    ~EngineDataInterface() override = default;
};

/**
 * @brief Engine Software Component
 * 
 * This SWC represents the application layer of an Engine Control Module (ECM).
 * In a real vehicle, this would be part of the powertrain control system.
 * 
 * Responsibilities:
 * - Monitor engine parameters (RPM, temperature, throttle)
 * - Send engine data to other ECUs via CAN
 * - Provide engine data to other SWCs via RTE ports
 * 
 * AUTOSAR Ports:
 * - EngineDataPort (Sender): Sends engine data to Body Control, etc.
 */
class EngineSWC : public SoftwareComponent {
public:
    /**
     * @brief Constructor
     * @param can_interface CAN communication interface
     */
    explicit EngineSWC(std::shared_ptr<CANInterface> can_interface);
    
    /**
     * @brief Destructor
     */
    ~EngineSWC() override = default;
    
    // AUTOSAR SWC lifecycle
    Std_ReturnType initialize() override;
    
    // Main runnable entity - called periodically by RTE/OS
    void runnable() override;
    
    // Port access functions (would typically be generated by AUTOSAR tools)
    Std_ReturnType writeEngineData(const EngineData& data);
    Std_ReturnType readEngineData(EngineData& data) const;
    
    // Getters for current state (for debugging/monitoring)
    const EngineData& getCurrentEngineData() const { return current_engine_data_; }
    uint32 getCycleCount() const { return cycle_count_; }
    
private:
    // CAN communication
    std::shared_ptr<CANInterface> can_interface_;
    
    // Engine simulation state
    EngineData current_engine_data_;
    std::mt19937 random_generator_;
    std::uniform_int_distribution<int> rpm_variation_;
    std::uniform_real_distribution<float> temp_variation_;
    
    // Timing and scheduling
    std::chrono::steady_clock::time_point last_execution_;
    uint32 cycle_count_;
    
    // Configuration
    static constexpr uint16 MIN_RPM = 800;   // Idle RPM
    static constexpr uint16 MAX_RPM = 6000;  // Redline RPM
    static constexpr uint8 MIN_TEMP = 80;    // Minimum operating temperature
    static constexpr uint8 MAX_TEMP = 120;   // Maximum safe temperature
    
    // Private methods
    void simulateEngineParameters();
    void sendEngineDataViaCAN();
    void updatePortData();
    
    // Simulation helpers
    uint16 simulateRPMChange();
    uint8 simulateTemperatureChange();
    uint8 simulateThrottlePosition();
};

} // namespace autosar

#endif // ENGINE_SWC_HPP